-- Create Oracle user
CREATE USER attendly IDENTIFIED BY attendly123;
GRANT CONNECT, RESOURCE TO attendly;
ALTER SESSION SET CURRENT_SCHEMA = attendly;

-- Admin Table
CREATE TABLE admin(
  admin_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR2(50) UNIQUE NOT NULL,
  password_hash VARCHAR2(255) NOT NULL
);

-- Attendance Table
CREATE TABLE attendance(
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_name VARCHAR2(100),
  date_marked DATE DEFAULT SYSDATE,
  status VARCHAR2(10)
);

-- Insert default admin (password: admin123)
INSERT INTO admin(username,password_hash)
VALUES('admin','$2b$10$6tQzVgXuvDJmZtX/NyTk6eZFeO1xX6gYY.8nV4ASXq1f/hQbQw7PS');
COMMIT;
